### PR TITLE
Menu for Unified Bed Leveling + other menu additions

### PR DESCRIPTION
**Pull request by Henri-J-Norden**
### Description/Benefits
When UBL is enabled in configuration.ini, the Level option is shown in the main menu, which opens a new UBL menu. The menu allows graphical control of much of the UBL functionality:

1. Enabling/disabling UBL (M420 S*)
2. Running the auto bed leveling process (G29 P1 and G29 P3 to fill in the edges)
3. Automatically applying a tilt to the existing mesh (G29 J) with a grid size configurable in the GUI
5. Manual tuning of each mesh point (i.e. manual leveling, similar to G29 P4), based on the ManualMesh menu
6. Saving/loading to slot 0
7. Changing the fade height (currently the value must be saved to EEPROM from a different menu)
8. Creating a new mesh with either values of 0 or NaN (undefined mesh)
9. Converting the current mesh into a plane (requires at least 3 not-NaN values)

A simple graphical mesh viewer is also included to visualize the current mesh (showing a 15x15 plane here):
image

Menu screenshots:
image
image

#### Edit:
The PR now contains additional features added to other menus as well:
1. Print statistics in Control/Info
2. Mesh viewer point value display support
3. Draw_Checkbox helper function to visually display boolean values
4. Cold extrude temperature and power-loss recovery control in Control/Advanced
5. Manual bed probe control in Move

### Configurations
Example configurations are available in `E3V2 Templates/UBL-*`. I have tested it in manual mode (no probe) and with a DIY servo probe, so hopefully other configurations should work too.

**NB: This change requires a display firmware update using the folder `Display firmware/DWIN_SET`, as new icons were included for the menu.** The .ICO packing/unpacking tool and original files for the new icons are included in `Display firmware`.

### CODE REVIEW

**Comment by Schnabulation** [comment]
Ok, this is AWESOME! I wanted to switch from bilinear leveling to UBL for a long time but couldn‘t get my head around UBL for now...

**Comment by Jyers** [comment]
This is some really great work you've done here. It might take me a bit to review it all, and I think I'll definitely have some questions about a few of the changes. The only real issue I see on first glance is the inclusion of new display icons. So far I have managed to avoid requiring the screen to be flashed, and although at some point it may be inevitable. I would like to avoid all users having to flash their screens for the sake of a menu many of them might never see based on their settings. A possible alternative if you really feel you need new icons, would be to store them under the name of some unused icons, that way the firmware is still compatible whether the screen is flashed or not.

**Comment by Henri-J-Norden** [comment]
Right, I was wondering why you hadn't already added any new icons! How about this: I added a new configuration option, CREALITY_DWIN_EXTUI_CUSTOM_ICONS, which can be enabled if you have also flashed the display. There is now a check in Draw_Menu_Item to ensure the requested icon is available and I also wanted to keep the Draw_Checkbox function I made working, so as a fallback it just uses rectangles and lines to draw a basic checkbox. This way custom icons can still be added and checkboxes used without affecting UI functionality/aesthetics of people who don't want to flash their display (too) much.

**Comment by t3chguy** [comment]
This is awesome and a huge step forward. It might be sane to break it up into smaller changes just for easier review.

**Comment by Henri-J-Norden** [comment]
> It might be sane to break it up into smaller changes just for easier review.

I suppose I could try that. I don't have much experience with pull requests though so would it, for example, make sense to have a PR with features dependent on something added in another PR?

**Comment by t3chguy** [comment]
Yeah stacking PRs is not uncommon. I think a foundational PR which adds the custom display firmware stuff e.g checkboxes and the like and then building this on top of that would be great.

Also means I can use the checkboxes in my PRs quicker :D

**Comment by Henri-J-Norden** [comment]
Hmm I opened the pull requests as listed above, but I don't think https://github.com/Jyers/Marlin/pull/135 is quite right... It also includes all the commits already in https://github.com/Jyers/Marlin/pull/134

**Comment by t3chguy** [comment]
@Henri-J-Norden I suggest clicking Edit on #135 and changing the base branch to your framework branch, then when #134 gets merged Github will automatically update the Base branch to that of where #134 was merged.

**Comment by Henri-J-Norden** [comment]
@t3chguy Interesting, but will that really work across repositories? When editing the base branch in https://github.com/Jyers/Marlin/pull/135, I don't see my `framework` branch at all: 
image

**Comment by t3chguy** [comment]
Argh it does break down across repos/forks. In any case, once #134 lands the commits/diff on #135 will fix itself.

**Pull request closed without merging**
