### PR TITLE
Added LCD backlight brightness control

### PR DESCRIPTION
**Pull request by corben2**
### Description

This change adds LCD backlight control by adding the following:

1. A new gcode command, to set the backlight brightness (M251 B##). For example a M251 B1 turns the brightness as low as it can go before going off completely. A M251 B0 is off. A M251 B255 is the max, and also the default.
2. A menu under the Control menu to adjust the brightness.
3. An option under the Tune menu, during a print, to turn the backlight off completely. It is turned back on with a press of the button, a power reset, or with any menu changes (for example, if an M600 happens). 
4. The brightness is also stored in EEPROM.

### Benefits

This gives increased control over the LCD. Adjusting the brightness or turning the backlight off completely is convenient, and can save energy.

The benefit of implementing it as a gcode, is that it can be controlled by Octoprint (I personally plan on just turning off the LCD backlight with a M251 B0 any time I startup the printer with Octoprint.) You could even do things like turning down the brightness at a start of a print, and turning it back up at the end in the print's gcode.

### Configurations

Any of the configs with CREALITY_DWIN_EXTUI enabled. Also CREALITY_DWIN_EXTUI_CUSTOM_ICONS if you want to test out the icons.

### Feedback

I'm open to any feedback. If anything needs changed let me know. Menu text, locations, icons, of course can all be changed. I considered some different design choices that may have been better. For example, having the brightness be a percentage rather then using the raw value.

### CODE REVIEW

**Comment by Legsmaniac** [comment]
I like this idea.  Nice one.

> For example, having the brightness be a percentage rather then using the raw value.

The percentage option is neat and tidy and easy to understand and get to grips with for the newbies but you lose an extra 155 steps of fine tuning control and that's a lot. The lowest setting (1%) would be 3 (2.55 rounded) whereas with raw value it's 1.  So whilst I do like percentage, I would personally opt for raw.  Although whether anyone would actually see the difference in brightness between 1 and 3 is debatable. 

Or what about a user choice option in the Advanced menu similar to the 00h00m option?

**Comment by Jyers** [comment]
I think a setting for percent vs raw is a little much, 100 steps will be plenty for most people. And if I find that 1% is too bright compared to 1/255, I'll just tweak that case so 1% corresponds to 1/255 to give the dimmest value without being off.

**Comment by joeclifford** [comment]
I've merged this to my local branch and have been testing it for a couple of days.

I do have some feedback:

1. The menu feels out of place in the the root of the control menu. I think it would make more sense to add it to the advanced menu where the majority of settings like this are currently found.

2. I think consistency is important when it comes to coding. There are another places in Marlin where the raw value between 0-255 is used, such as fan speed, and isn't converted to a percentage. Converting to a percentage also introduces a disconnect between what is stored in the eeprom and what is displayed in in the GUI.

**Comment by joeclifford** [comment]
@Legsmaniac in respect to your statement

> Although whether anyone would actually see the difference in brightness between 1 and 3 is debatable.

There is a visible difference when changing from 1 to 2 to 3, even in a well lit room. The change isn't much (as it is ~0.4%), but it is clearly visable.

**Comment by Jyers** [comment]
Thanks for the feedback, always good to have others testing PRs. I agree the item should probably be moved to advanced, and after thinking about it I also quickly came to the conclusion that the raw 255 steps is the best option.

**Comment by corben2** [comment]
Thanks for the feedback and testing everyone. I can add a commit later today that moves the brightness setting to advanced, any preference on where specifically in advanced? Also, right now the option to turn the backlight off is at the top of the tune menu, should I move that at all?

**Comment by Jyers** [comment]
I would say top of the advanced menu, bottom of the tune menu.

**Comment by tititopher68** [comment]
Contrary to what @Jyers thinks, and with all due respect for his work, the initial choice of placement of this feature strikes me as much smarter.
Why ? I think the Advanced menu is dedicated to features that we have little use. The change in brightness, much more.
Ditto in Tune, at the beginning of the menu, it would be better for the same reasons and without risking to validate by mistake another parameter ...
This is just an opinion ...

**Comment by corben2** [comment]
I know this PR is closed, I can open an issue if that would be better. One thing I was careful about in my original code was to not have the backlight stay off if something like a M600 (filament change) happened during a print. I just tested it with the changed version, and the backlight stays off and you can't really see the screen and may have to power cycle the printer to get the backlight back on (or try and fumble around with the menu blindly).

Your code is definitely a lot cleaner. Thanks for all the work you've put into this firmware, it's been great to use.

**Comment by Jyers** [comment]
Good point, I'll make it turn on the backlight for popups. And thank you for all your work on this, its a great feature!

**Pull request merged**
