### PR TITLE
Adds menu for showing stored mesh values

### PR DESCRIPTION
**Pull request by kjeldahl**
### Description
This code adds a menu "View Mesh" under Control ->
Advanced Settings.
Entering this menu will display a table of the stored mesh
values if any. It can display up to 5 values on the x-axis.

The menu is added if HAS_MESH is defined.

### Benefits

It makes it possible to see the zoffsets stored in the mesh when a mesh has been stored using the
manuel bed levelling method

### Configurations

Enable AUTO_BED_LEVELING_BILINEAR or MESH_BED_LEVELING to enable HAS_MESH

### CODE REVIEW

**Comment by Jyers** [comment]
Totally on the wrong branch for that commit. God I'm bad at github. Will hopefully get to reviewing this soon, looks really nice. Thanks for the work!

**Comment by kjeldahl** [comment]
You are welcome. You would probably want to look at the preprocessor variables I am using as I was a bit uncertain at those and perhaps the location of the menu. It might make more sense to put it in the top level levelling menu or it might not :-)

No worries about github I use it daily and still have to lookup anything but the most basic commands.

**Comment by Tuncay-Ayhan** [comment]
Looks great! Would be awesome if you could edit them also in the same menu.

**Comment by kjeldahl** [comment]
@Tuncay-Ayhan I do not think it is possible. The API only allows for updates to the mesh during the levelling process.
You might want to take a look at UBL instead.

**Comment by Tuncay-Ayhan** [comment]
> @Tuncay-Ayhan I do not think it is possible. The API only allows for updates to the mesh during the levelling process.
> You might want to take a look at UBL instead.

Thanks for your reply. I meant like as a sub-menu in the mesh menu. On the fly with going back to a previous point would be awesome. But I think that's another discussion.

**Comment by Jyers** [comment]
I'm currently working on an implementation that allows the use of the UBL mesh viewer with all leveling options, so I'm going to close this.

**Pull request closed without merging**
