### PR TITLE
Better presentation for service warnings and reset printer counter

### PR DESCRIPTION
**Pull request by tiagofreire-pt**
### Requirements

First, enable the print counter, in `configuration.h`:

```
#define PRINTCOUNTER
```

### Description

More human readable and pleasant way to present service warnings. Also, added an option to reset this printer counter, into the buttom of the `info` menu.

### Benefits

service_warning

### Configurations

As proposed.

### Related Issues

N/A

### CODE REVIEW

**Comment by tititopher68-dev** [comment]
@tiagofreire-pt @Jyers
and add this : 
https://github.com/Jyers/Marlin/discussions/1580#discussioncomment-1597625

**Comment by tiagofreire-pt** [comment]
@tititopher68-dev , thanks for the tip!

Just added a new commit.

**Comment by tititopher68-dev** [comment]
@tiagofreire-pt 
You should have an issue if PRINTCOUNTER is disable during compilation.
You forgot a conditional.
#if ENABLED(PRINTCOUNTER)
case INFO_RESET_PRINTCOUNTER:
           if (draw) {
             Draw_Menu_Item(row, ICON_HotendTemp, F("Reset Print Counter"));
           }
           else {
             print_job_timer.initStats();
             ui.reset_status();
             AudioFeedback();
           }
           break;
#endif

**Comment by tititopher68-dev** [comment]
@tiagofreire-pt 
Try this fix for maple -> timers and pwm HAL :
Just copy the 2 files timers.h and fast_pwm.cpp in Marlin/src/HAL/STM32F1
These Files are compatible with Jyers Releases from v1.3.4 to actual v2.0.1
This should prevent some Hotend crash on the Bed, some issues with Endstop, BLTouch and LCD Glitch...
[Timers_and_Maple_pwm_fix.zip](https://github.com/Jyers/Marlin/files/7651251/Timers_and_Maple_pwm_fix.zip)

**Comment by mosheas** [comment]
You can reset counter by G-code, very simple.

**Pull request closed without merging**
