### PR TITLE
Add support for Host Action Pause/Cancel

### PR DESCRIPTION
**Pull request by t3chguy**
Pause/Stop work, Resume support in the rewrite looks partial so doesn't work here either.

### CODE REVIEW

**Comment by Schnabulation** [comment]
So does that mean that the Pause and Stop buttons work when printing from OctoPrint?

**Comment by t3chguy** [comment]
Yes. If you have HOST_ACTION_COMMANDS enabled

**Comment by Schnabulation** [comment]
Oh, I didn't even know about HOST_ACTION_COMMANDS. Is there any other futher function when defining HOST_ACTION_COMMANDS or does it only allow to pause and stop the OctoPrint job from the printer with your firmware?

**Comment by t3chguy** [comment]
https://reprap.org/wiki/G-code#Action_commands outlines all that is possible, this PR only implements Pause/Stop.

**Comment by Jyers** [comment]
Because I have made quite a few changes since this was opened and the conflicts were a little much I decided to make a new commit for them. So they should now be implemented. Also the resume popup in the code is for power loss recovery and not print resume.

**Pull request closed without merging**
