### PR TITLE
Custom Color Themes Additions

### PR DESCRIPTION
**Pull request by AngleV**
@Jyers 

I did some more adittions if you 're interesting.

1. Added one more element so the user can change the Menu Top Background/Text Color. See photo attached.

175344722_162244402448211_1042594413228778783_n

2. Added one more element to the IMHO ugly split line above the coordinates info.

3.  Added the Black Color only to some of the elements such the menu split line, top menu background etc. User can choose it to achieve no visible effect. See photo attached.

175394049_899923597527133_8548755768432285274_n

4. Added Cyan Color 

Thank you for your awesome work! Keep coding and god bless you

### CODE REVIEW

**Comment by AngleV** [comment]
> @AngleV
> I want to download and install this file, what should I do?

Which file are you referring to?

**Comment by gokhanselen** [comment]
@AngleV
I want to make my screen like this your color themes
what should I do

**Comment by AngleV** [comment]
> @AngleV
> I want to make my screen like this your color themes
> what should I do

You can download the source files and compile them to get the firmware.
Search Google for how to compile marlin firmware on your own

**Comment by Tw0bit** [comment]
It might be in the 1.3.1 build - https://github.com/Jyers/Marlin/releases/tag/v1.3.1

I have not tried, but maybe...

**Comment by gokhanselen** [comment]
@Jyers
AngleV  
Merhaba 1.3.1 için teşekkür ederim
Yeni menü simgeleri  yok mu ? :)
(Hello, thank you for 1.3.1
No new menu icons? )

**Pull request merged**
