### PR TITLE
New_features in developpement

### PR DESCRIPTION
**Pull request by tititopher68-dev2**
To Jacob (Jyers) from Christophe (tititopher68-dev):

- bugfix-marlin in date 14/03/2022 merged
- a lot of fix about Z-Offset, ManualMesh, UBL Noprobe, Host keyboard, etc...

**_New features ->_**

- Firmware restructuring,
- EEprom structure modifications,
- Extensions of UI customization possibilities,
- Modification in the BaudRate UI (250000 or 115200)
- Editable parameters: PROBING_MARGIN, Nozzle Park Point, Z probe Feedrate Fast and Slow (to increase compatibility with the CRTouch), Filament Unload feedrate, filament fast load feedrate,
- Reverse dir extruder in the UI,
- Add an indicator Leveling active,
- Fan display in value (0-255) or in percent (0-100%),
- 3 possible options for setting the Z-Offset including OnClick (actual) and OnLive,
- A new mode for Bed Corner Leveling,
- Added a FW Retraction menu (in Tune and in Control menu),
- Management of the High Speed ​​mode for the BLTouch/CRTouch/3DTouch,
- Added Screen Lock function,
- Addition of an endstop diagnostic tool/function (x,y,z, runout sensor),
- Extensions of the Reset Settings functions (the firmware will be reset to update if necessary),
- Added a Reboot Printer function,
- Gcode preview thumbnails,
- gcode preview header,
- Choice in the UI of the type of Runout sensor (LOW, HIGH or Motion like BTT SmartSensor) with an associated Gcode M591 R, S, H, L, D, P replacing M412.
- Added new popups,
- Various additions to/and restructuring of existing menus,
- Added new Gcodes C108 (Cancel a Wait for User without an Emergecy Parser), C125 X Y Z (Nozzle park points), C510 (Look screen), C562 E (invert dir extruder), C851 M F S (probe margin and Z probe feedrate).

### CODE REVIEW

**Comment by CRCinAU** [comment]
You probably should restore the authorship comments in files that you've changed function names on...

Given that it may well be common code, it would be more useful to export those functions to a common set of .c / .h files and drop them from being individually in each UI flavour...

Duplicated code with only changed function names doesn't really help the project.

**Comment by tititopher68-dev** [comment]
@CRCinAU 
You have my answer on the Discord Marlin.  I even think to delete the other UI (proui, etc.) useless here, because we are not on the GitHub Marlin.

If you look a little more on the web, you will find that Mriscoc has taken a lot of things from a dev who had developed a new interface, 18 months ago already, by creating additions to the basic DWIN functionalities of Creality and others  bases that Mriscoc took over for the visualization of the points of the mesh in progress (but that Mriscoc hid it in his famous libraries abl/mbl_proui.a, I remind you that he kept telling anyone who wanted to hear  that he has always published the sources of his binaries which have been shown to be lies, lies in which he prefers to take refuge by pretending to be a victim), that Mriscoc uses Prusa MK3 code bases, etc.  .. In the documentation will be, as I have always done, quoted the different sources and inspirations.

Finally, I would never give endorsement or publicity to this person who bans users as soon as we disagree with him and his practices, who deletes any post evoking his practices or any information on our developments around the firmware in this  GitHub under cover of his hidden moderator handle under reddit.com.

**Comment by CRCinAU** [comment]
Not buying your argument - and for the record, I don't "support" anyone - code speaks more than peoples ego or opinions.

I have a hard time in accepting that the Marlin code:
```
void draw_es_label(FSTR_P const flabel=nullptr) {
  DWINUI::cursor.x = 40;
  if (flabel) DWINUI::Draw_String(F(flabel));
  DWINUI::Draw_String(F(": "));
  DWINUI::MoveBy(0, 25);
}
```

is not the basis of your code:
```
void draw_ends_label(FSTR_P const flabel=nullptr) {
  JYERSUI::cursor.x = 40;
  if (flabel) JYERSUI::Draw_String(F(flabel));
  JYERSUI::Draw_String(F(": "));
  JYERSUI::MoveBy(0, 25);
}
```

This does indeed seem to be entire files taken, with only the authorship details removed, basic details changed, from code that is already in the Marlin code base.

See:
https://github.com/MarlinFirmware/Marlin/blob/2.0.x/Marlin/src/lcd/e3v2/enhanced/endstop_diag.cpp
vs
https://github.com/Jyers/Marlin/blob/223899bc86daf076d7ab4ffa2d7453f743beb8e4/Marlin/src/lcd/e3v2/jyersui/diag_endstops.cpp

You can't tell me those are two, totally different innovations that just happen to differ by a few small parts?

**Comment by tititopher68-dev** [comment]
@CRCinAU 
There's something you don't want to understand.  On my local version under development, there is no more proui, or CrealityUI or MarlinUI.

 I have a large body of evidence where it is seen that Mriscoc took over lots and lots of code and bits of code into its UI without further reference to the core authors.  I absolutely do not deny that for these 2 files, it is taken from Mriscoc which itself took it from Prusa.  But given that he continues to hide code that must remain open and whose sources are partly that of other devs without quoting them somewhere and given his behavior, I refuse to quote him.  But I will put the reference to Prusa and explain why in 3 lines, I refuse to name and quote Mriscoc.

You have never been very critical of Mriscoc, including on the evidence that has been denounced concerning Mriscoc and you have always looked for the loophole to exculpate him.  You even allowed yourself to say on the Marlin Speech that given that I supposedly posted nothing on Marlin, I had no right to finally denounce anything.

 I've never seen you on Mriscoc's GitHub asking about GPL compliance.

 I invite the community here to go to the Discord Marlin and see what I say.  What a number have already done!

 Here in this community, the code is completely open and shared, editable by anyone who then shares their code and so on.

  End of discussion, otherwise it will sound like trolling...

**Comment by CRCinAU** [comment]
Ok, so you don't get to decide who code credits go to. If you lift a file from the Marlin repo (which you admit), then you have also removed authorship information from code in the Marlin repo to add it to your own.

As such, given your hardon for GPL compliance, then that behaviour violates section 5 part A of the GPLv3.

It also violates section 7 part b which covers:
> Requiring preservation of specified reasonable legal notices or author attributions in that material or in the Appropriate Legal Notices displayed by works containing it;

**Comment by tititopher68-dev** [comment]
@CRCinAU 
Why don't you address (and never addressed that) also that to Mriscoc?
 So I had anticipated and posed the question directly to the founders of the GNU GPLv3.  From the moment the original author (Mriscoc) himself does not respect the GPLv3 license, he then has no rights over it and loses his rights.  So GNU advised me to name only the 1st source Prusa or only Marlin, but authorizes me not to cite Mriscoc!

**Comment by CRCinAU** [comment]
The code was submitted to the Marlin repository in compliance with the GPL. Your copy of the modified sources does not.

**Comment by tititopher68-dev** [comment]
@CRCinAU 
Alas here is where the decisions of Thinkyhead led to anything!  There are at least 4 versions of these identical files (2 on the repositories of Mriscoc and 2 on those of Marlin) not having the same licenses!  So if I base myself on Mriscoc's GitHub source which does not respect the GPL, then he has no rights.  In short, the source code used is partly taken from the source code of Prusa.  I will only cite this source as Marlin should have done!  And then I'm fully GPL compliant.  Marlin ended up validating code, either not respecting the GPL, or whose base belongs to Creality, codes that Mriscoc attributed to himself in all existing sources.
 The solution would have been to withdraw Mriscoc's contributions until he came into compliance.  If Mriscoc respected the GPL and Marlin, we wouldn't have these nasty exchanges.

**Comment by Dids** [comment]
Related: https://github.com/MarlinFirmware/Marlin/pull/23878

See licensing comments from @thinkyhead.

**Comment by tititopher68-dev2** [comment]
@CRCinAU 

> As you acknowledge Mriscoc as the author, and therefore copyright holder of the file in question, he may decide under the same section of the GPL to terminate your license to use those specific files permanently. This would be outside the responsibility of the Marlin project and be entirely his decision based on the code he submitted - and not the entire Marlin project. You would then be required to seek permission from Mriscoc to use those files again.

Once again nonsense! You interpret things as it suits you and demonstrate your complacency with a developer who does not respect the Marlin license. At least admit it! **_I do not recognize Mriscoc as the original author of this file based on original Prusa code under GPL!_**
And then what, you are threatening me, Thinjkyhead has hijacked its own application of its license by letting Mriscoc do it, better even sponsoring Mriscoc and helping him to circumvent it and despite this, Mriscoc continues to disrespect it and Marlin.
I don't recognize Mriscoc as the original author of this file based on original Prusa code under GPL!

**Comment by Dids** [comment]
> @Dids
> 
> > Related: [MarlinFirmware#23878](https://github.com/MarlinFirmware/Marlin/pull/23878)
> > See licensing comments from @thinkyhead.
> 
> Regarding the 2 files, I never cited myself as the author! So in this, I never appropriated the rights of anyone including this dev who continues to hide code to remain open as the GPL requires! But i can't cite a pseudo author who doesn't respect Marlin licence GPL. Now I have restored the original providing source of the code of these 2 files and do not have that of this dev (code which obviously must be adapted to the screens, those of Prusa are different from DWIN).

Sorry, I didn't mean to imply you did, I just wanted to provide more context for everyone reading this, including what other developers are saying about mriscoc's attempts to alter, modify or mix licenses, in essence trying to copyright derivative work with slight alterations.

**Comment by tititopher68-dev** [comment]
A friend of mine's corporate IT security department did some research.  It appears that Mriscoc, CRC, the famous moderator from reddit.com NEDM64 and the nickname Though-Fuel-3493 used the same IP to connect and intervene.  It seems to be the same people!

**Comment by ellensp** [comment]
@tititopher68-dev your clearly off your meds!
CRC is in Australia
Mriscoc is in Lima, Peru
Your IT friend is either a moron, a fraud or made up (I suspect the latter)

**Comment by tititopher68-dev** [comment]
> @tititopher68-dev your clearly off your meds! CRC is in Australia Mriscoc is in Lima, Peru Your IT friend is either a moron, a fraud or made up (I suspect the latter)

Not CRCinAu of course but a nickname CRC ! And the insults, you can keep it to yourself!  OK !

**Comment by tititopher68-dev2** [comment]
Given the stink balls emitted by people supporting Mriscoc (concerning this character, I let you read here #1909), I move this project to another platform and under another name.  Jacob will have access in order to be able to calmly develop, improve and finalize the new functionalities.

**Comment by HAPSagan** [comment]
You say you will move the project and change the name.  How can we who appreciate your work and want to follow / take part in it in the future find it?  Best regards, Peter

**Pull request closed without merging**
