### PR TITLE
Fix compliling SKR E3 Turbo

### PR DESCRIPTION
**Pull request by tome9111991**
Fix for E3 Tubo can compile now thank to @eohl79
got only some warrnings but firmware works

should fix some other board from LPC176x 
SKR V1.4 Turbo works also

With Creality V4 board i got no error/warrning durring compiling
but should test display work correct before merge

### CODE REVIEW

**Comment by Jyers** [comment]
This is really do to some regression in the firmware as a whole that I need to fix. If after fixing it's still broken I'll use this, but hopefully it won't be needed if all goes well. Thanks for the PR though!

**Comment by Jyers** [comment]
Could you give this a try now without you're changes? The latest commit has brought us completely up to date with Marlin so it might just work 🤞

**Comment by tome9111991** [comment]
Yes I can try later maybe in 12 hours

**Comment by tome9111991** [comment]
@Jyers 
I have still same error
118365360-bcae5780-b59c-11eb-9828-87f45abe1712


With default branch i have no erros because i can't find
`while (LCD_SERIAL.availableForWrite() < 32) { // wait for serial to be available without blocking and resetting the MCU`

`while (!LCD_SERIAL && PENDING(millis(),serial_connect_timeout)) { /*nada*/ }`
In code

**Comment by Jyers** [comment]
Interesting, okay I'll check up on it after work and probably get this merged 🚀

**Comment by eohl79** [comment]
The issue is with LPC1768 serial HAL layer is using the ForwardSerialClass



 

Hence I needed to make the following changes to get the FW to work:


 



 

Attached are my config files I have been tinkering with which works with Octoprint and the Creality display so far.

 

Regards,

Edmund

**Comment by tome9111991** [comment]
I think default branch is working with
https://github.com/MarlinFirmware/Marlin/blob/2.0.x/Marlin/src/lcd/dwin/dwin_lcd.cpp

Look at line 90


PR
https://github.com/MarlinFirmware/Marlin/pull/20738

**Pull request closed without merging**
