### PR TITLE
GitHub Actions

### PR DESCRIPTION
**Pull request by Sennevds**
So I saw you create custom firmwares based on the config files you also delivered.
Here are some changes so every time you check in it automatically starts to build and pushes the new bin files.
If you want to create a new config (like the 5x5 grid) the action needs to be changed.

If you don't want this just don't merge :) Just thought I could help you out!
I've changed some names of the bin files and folders so it was a bit easier to code the GH actions!

### CODE REVIEW

**Comment by Jyers** [comment]
Oh wow, this is really really nice of you! I was actually just about to update the discussion post on this issue about how I am writing a PowerShell script to do the builds for me. The only thing that I see as a benefit of my method over this is that if I wanted to have say a 4.2.7 version for each of these I'd need templates for all of those, where as with PowerShell I can do a string replace. If you have a suggestion of how that could work with GitHub actions I would love to hear it as I would feel really bad if all of this work went to waste. Thank you so much for your time, this is awesome!

**Comment by t3chguy** [comment]
You can use a matrix configuration to generate all the permutations and then just use them as env vars: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstrategymatrix

**Comment by Sennevds** [comment]
It's my first time working with github actions(use azure devops for work). I will check @t3chguy url to make it better. 
Github actions are just linux commands you execute so you could easily do a string replace.

**Comment by Jyers** [comment]
@Sennevds As long as you haven't started already, I think I'll take a crack at adapting your workflow code with @t3chguy matrix idea to see if I can manage a pretty sleek solution. I'll keep this updated if I run into any issues

**Comment by Sennevds** [comment]
> @Sennevds As long as you haven't started already, I think I'll take a crack at adapting your workflow code with @t3chguy matrix idea to see if I can manage a pretty sleek solution. I'll keep this updated if I run into any issues

I haven't started on using the matrix strategy. I was thinking of trying it today but if you want it to do it yourself go ahead.

**Comment by Jyers** [comment]
I finished the workflow file last night and it works great! Using the matrix configurations it is able to build a ton of different configurations super efficiently and in parallel! Working on it made me realize that I really shouldn't be putting the .bins in the source code. So from now on they are going to be in the releases section of GitHub. Thank you guys for all the help, this is going to make my life so much easier :)

**Comment by t3chguy** [comment]
> Thank you guys for all the help, this is going to make my life so much easier :)

Just as you have made ours with a usable DWIN screen :D

**Pull request closed without merging**
