### PR TITLE
Custom Colors Themes

### PR DESCRIPTION
**Pull request by AngleV**
Since we have an colour LCD why should not have the opportunity to change the UI Color Scheme to our personal preference?

This code adds a menu "UI Color Settings" under Control -> Advanced Settings.
Entering this menu will display a list of  available UI elements that you can change the color such as the cursor color the highlight box border color and so on.

173042446_280396726972664_3600982558112871947_n

Clicking each one of this and a list of available colours appears.
172897437_444447173485188_1364461883811633124_n

### Benefits
User can select the colour of his personal preference.
172702310_268547484919499_8484653453228849940_n

### Configurations
No changes to the default ones.

### Related Issues

Due to lack of how Marlin works and poor knowledge of C++ i am not sure if my work is correct. Also there is one main issue.
It seems that the EEPROM settings area is beeing loaded after the UI and this has a result that elements that allready been drawed not getting the corect color until their value changes

Also it needs some new icons for the color list and the section items. For now i used one of the available just for the implement sake.

if you find it interest you can fix it better than me and merge it. :-)

Also i would like to say that i am new to github operations and i didnt know how not to include my configurations files in the commit.

Thank you

### CODE REVIEW

**Comment by Legsmaniac** [comment]
Cool! I like this. This would set Jyers apart from all the others. More so than it is already. 👍

**Comment by Giadej** [comment]
Very, very cool! 
Would you like to share the 9.ico file you edited?

**Comment by Jonny11bonk** [comment]
I would like to see a video tutorial how you add these kinds of options and how I can add my custom things into the GUI like text, image, button, menus.

**Comment by Jyers** [comment]
@Mineplayerminer If you have a basic knowledge of programming and C++ it's not too difficult based on how I've set it up. Check out `Marlin\src\lcd\extui\lib\creality_dwin\creality_dwin.cpp` and `Marlin\src\lcd\extui\lib\creality_dwin\creality_dwin.h`. The function `Menu_Item_Handler` handles most of the menu features.

**Comment by Jonny11bonk** [comment]
> @Mineplayerminer If you have a basic knowledge of programming and C++ it's not too difficult based on how I've set it up. Check out `Marlin\src\lcd\extui\lib\creality_dwin\creality_dwin.cpp` and `Marlin\src\lcd\extui\lib\creality_dwin\creality_dwin.h`. The function `Menu_Item_Handler` handles most of the menu features.

Can I use the VS Community or the VS Code to edit it?

**Comment by AngleV** [comment]
> Very, very cool!
> Would you like to share the 9.ico file you edited?


Sure.  Here you are

https://drive.google.com/file/d/1a2x-StrkKZxCPnASHgdXZkMtvmOiHiXO/view?usp=sharing

**Comment by gokhanselen** [comment]
Hello. What should I do to make the menu beautiful?

**Comment by tititopher68** [comment]
@AngleV,

Hello, Thank you very much for this nice job !
I've solved a lot of your issues, if you're interested...

**Comment by AngleV** [comment]
@tititopher68 

Of course and i'm interested. 
I would be delightful to see your solution to this topic

**Comment by Jyers** [comment]
You can leave this as is for now. I think I have all the touchups I want to make lined up. Nothing major just some cleanup and optimization. Great work on this by the way!

**Comment by AngleV** [comment]
@Jyers 

Great. Thank you!!!
In the near future i'm planning to make some more changes that i have in mind for a more aesthetic improvement of the overall user interface experience.

**Comment by gokhanselen** [comment]
> > Çok, çok havalı!  Düzenlediğiniz 9 .ico dosyayı paylaşmak ister misiniz?
> 
> Emin. İşte
> 
> https://drive.google.com/file/d/1a2x-StrkKZxCPnASHgdXZkMtvmOiHiXO/view?usp=sharing

AngleV I have poor knowledge. Can you describe how I should upload these files?

**Comment by Bukken5150** [comment]
> > > Çok, çok havalı!  Düzenlediğiniz 9 .ico dosyayı paylaşmak ister misiniz?
> > 
> > 
> > Emin. İşte
> > https://drive.google.com/file/d/1a2x-StrkKZxCPnASHgdXZkMtvmOiHiXO/view?usp=sharing
> 
> AngleV I have poor knowledge. Can you describe how I should upload these files?

You replace the 9.ICO file in the Display firmware/DWIN_SET/ folder with the one AngleV has made.
Then copy the DWIN folder to a sd card and use that to flash your screen.

**Comment by gokhanselen** [comment]
Bukken5150 
I'm afraid of doing wrong and spoiling because my knowledge is poor
shouldn't i do it as follows

To update the graphics and icons on the display:

Copy the folder to an SD card, remove the back cover of the display and insert the card into the microSD slot on the back of the display unit's PCB.DWIN_SET
Power on the machine and wait for the screen to change from blue to orange.
Power off the machine.
Remove the SD card from the back of the display.





Ekrandaki grafikleri ve simgeleri güncelleştirmek için:

Klasörü bir SD karta kopyalayın, ekranın arka kapağını çıkarın ve kartı ekran biriminin PCB'sinin arkadaki microSD yuvasına takın.DWIN_SET
Makineyi çalıştırın ve ekranın maviden turuncuya değişmesini bekleyin.
Makineyi kapatın.
SD kartı ekranın arkasından çıkarın.
Başarılı bir flaşı onaylamak için açık.

**Comment by gokhanselen** [comment]
Doesn't have a ready DWIN_SET file
ready to install

**Comment by Bukken5150** [comment]
> Bukken5150
> I'm afraid of doing wrong and spoiling because my knowledge is poor
> shouldn't i do it as follows
> 
> To update the graphics and icons on the display:
> 
> Copy the folder to an SD card, remove the back cover of the display and insert the card into the microSD slot on the back of the display unit's PCB.DWIN_SET
> Power on the machine and wait for the screen to change from blue to orange.
> Power off the machine.
> Remove the SD card from the back of the display.
> 
> Ekrandaki grafikleri ve simgeleri güncelleştirmek için:
> 
> Klasörü bir SD karta kopyalayın, ekranın arka kapağını çıkarın ve kartı ekran biriminin PCB'sinin arkadaki microSD yuvasına takın.DWIN_SET
> Makineyi çalıştırın ve ekranın maviden turuncuya değişmesini bekleyin.
> Makineyi kapatın.
> SD kartı ekranın arkasından çıkarın.
> Başarılı bir flaşı onaylamak için açık.

No problem.
That's the correct way to update displays firmware, sorry for not pointing that out. It is also recommended to wait 30 seconds after the screen has turned orange before you power off the machine.

**Comment by gokhanselen** [comment]
Bukken5150
Sorry i don't know english i am using google translate
Is there no DWIN_SET file ready with the menu changed? Let me upload it
Bukken5150 thank you for your help

**Comment by Bukken5150** [comment]
> Bukken5150
> Sorry i don't know english i am using google translate
> Is there no DWIN_SET file ready with the menu changed? Let me upload it
> Bukken5150 thank you for your help

DWIN_SET is not a file but a folder. You have to copy the folder to your sd-card.
You can follow the steps in this video https://www.youtube.com/watch?v=Jswzrh2_ekk
Hope this helps

**Comment by gokhanselen** [comment]
Bukken5150
Thank you now I learned how to install
When I put 9 .ICO files in DWIN_SET closer it will be ok.

**Comment by tititopher68** [comment]
@AngleV , it's done in pull request : https://github.com/Jyers/Marlin/pull/515

**Comment by gokhanselen** [comment]
> > Çok, çok havalı!  Düzenlediğiniz 9 .ico dosyayı paylaşmak ister misiniz?
> 
> Emin. İşte
> 
> https://drive.google.com/file/d/1a2x-StrkKZxCPnASHgdXZkMtvmOiHiXO/view?usp=sharing
Bu dosyayı DWIN_SET in icine mi kopyalıyacam,

**Comment by Jyers** [comment]
I wasn't intending on that big of an overhaul, but this PR inspired me to make a new option selection system for settings like this. I'm just going to reset the configs and encoder file back to default and then I'll get this merged

**Pull request merged**
