### PR TITLE
Christophe's Modification

### PR DESCRIPTION
**Pull request by Jyers**
This PR is to look over the modification made by @tititopher68 and hopefully get some of his additions merged.

### CODE REVIEW

**Comment by tititopher68** [comment]
Hello Jacob, 

How can I put the other changes for version 1.2.3.d here?

**Comment by tititopher68** [comment]
Hello Jacob, 
I integrated your last updates in "my last version ...". The coding principle of the Backlight function is really interesting (even if I do not find the locations judicious ... just personal opinion). However the use is impractical, turning the button to "turn off the screen" does not seem ideal to me. In addition, on exiting the black screen, you have set the value to 1, but on the screen it remains displayed at 0 as long as you do not exit the menu or change the value. ..Also I made some adjustments by limiting the range from 1 to 255 and adding an item "Turn LCD OFF" which keep the previous value well ... both in Control, etc ... and in Tune to keep the spirit of what you wanted to do. The code, for that, is perhaps not very elegant but still effective. I'm sure you can do better than I do.

**Comment by Jyers** [comment]
Okay, I'll integrate your newest changes into the PR. Thank for checking, and yes it would probably best to direct users to the github so modification don't have to go through multiple stages to get integrated. Either way, keep up the great work!

**Comment by tititopher68** [comment]
BLTouch1
BLTouch2
BLTouch3
PIDAutotune1
PIDAutotune2
PIDAutotune3
PIDAutotune4
ViewMesh1
ViewMesh2


I am sending in your mailbox 
(jyers.m@gmail.com) the build version 1.3.1.a which includes new modifications as for the PID Autotune part.
They respond to requests from francophones.
Hoping that this can inspire you….

In any case, an excellent job!
Best regards,

@tititopher68

**Pull request closed without merging**
